#!/bin/sh

set -e

echo "      _       _         __ _ _"
echo "   __| | ___ | |_      / _(_) | ___  ___"
echo "  / _\` |/ _ \| __|____| |_| | |/ _ \/ __|"
echo " | (_| | (_) | ||_____|  _| | |  __/\__ \\"
echo "  \__,_|\___/ \__|    |_| |_|_|\___||___/"
echo ""

echo "--- Installing dot-file for vim and tmux ---"
cd ~


if [ -f ~/.vimrc ];
then
	echo "> backing your old .vimrc file to ~/vimrcOLD.."
	sudo mv ~/.vimrc vimrcOLD
	echo "..done"
	echo "> copy the new .vimrc file "
	cp ~/dotfiles/.vimrc ~/
	echo "..done"
else
	echo "> copy the new .vimrc file "
	sudo cp ~/dotfiles/.vimrc ~/
	echo "..done"
fi

if [ -f ~/.tmux.conf ];
then
	echo "> backing your old .tmux.conf file to ~/tmux.confOLD.."
	mv ~/.tmux.conf tmux.confOLD
	echo "..done"
	echo "> copy the new .vimrc file"
	cp ~/dotfiles/.tmux.conf ~/
	echo "..done"
else
	echo "> copy the new .tmux.conf file"
	cp ~/dotfiles/.tmux.conf ~/
	echo "..done"
fi

echo "> Copy YouCompleteMe configuration file.."
cp ~/dotfiles/.ycm_extra_conf.py ~/
echo "..done"

echo "> Copy colorschemes.."
cp ~/dotfiles/vim/colors/. ~/.vim/colors/ -R
echo "..done"

sudo apt-get install build-essential cmake
sudo apt-get install python-dev

echo "> Installing Vim Plugins.."
vim +PluginInstall +qall
echo "..done"

echo "> Compiling YCM with semantic support for C-family languages.."
cd ~/.vim/bundle/YouCompleteMe
./install.py --clang-completer
echo "..done"
echo ""
echo ""
echo "Installation done"
